### ISSUE TITLE
Repl Error

### ISSUE THREAD

**Issue by ghost** [Major-Thrust/Discordjs-MusicBot#23]
node index.js
internal/modules/cjs/loader.js:818
  throw err;
 node index.js
internal/modules/cjs/loader.js:818
  throw err;
 node index.js
internal/modules/cjs/loader.js:818
  throw err;
 node index.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:events'
Require stack:
- /home/runner/Discordjs-MusicBot/node_modules/discord.js/src/client/BaseClient.js
- /home/runner/Discordjs-MusicBot/node_modules/discord.js/src/index.js
- /home/runner/Discordjs-MusicBot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/Discordjs-MusicBot/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/Discordjs-MusicBot/node_modules/discord.js/src/client/BaseClient.js',
    '/home/runner/Discordjs-MusicBot/node_modules/discord.js/src/index.js',
    '/home/runner/Discordjs-MusicBot/index.js'
  ]
}
exit status 1

**Comment by DevClayy** [comment]
Upgrade your node.js version. I personally use discord.js@12.5 
`npm i discord.js@12.5` As replit does not support Node.js@16 - only node v.12.2

**Comment by AKPR2007** [comment]
@Loco633 type `npm i` in console before executing
